spring:
  datasource:
    url: jdbc:mysql://192.168.71.101:3306/user_center?characterEncoding=utf-8
    hikari:
      username: yuyongtao
      password: yuyongtao
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

#  cloud:
#    nacos:
#      discovery:
#        # 指定nacos server的地址
#        server-addr: localhost:8848
#        # 指定namespace
#        # namespace: 56116141-d837-4d15-8842-94e153bb6cfb
#        # NJ
#        # 指定集群名称
#        cluster-name: BJ
#        metadata:
#          instance: c
#          haha: hehe
#          version: v1
#  application:
#    # 服务名称尽量用-，不要用_，不要用特殊字符
#    name: user-center
#server:
#  port: 8081